use  concert;
create table EPT(
EPID INT (30) NOT NULL,
EPNAME CHAR(150),
EP_ADDRESS CHAR(150),
EP_PHONE_NUMBER INT(11),
EP_CAPACITY INT(10) NOT NULL,
PRIMARY KEY (EPID)
);

create table COT(
COID INT AUTO_INCREMENT NOT NULL,
CONAME CHAR(150),
COSINGER CHAR(100),
COSTARTTIME TIME
COENDTIME TIME,
PRIMARY KEY (COID)
);

create table EPCOT(
EPID INT(10) NOT NULL,
COID INT(10) NOT NULL,
EPCO_TIME TIME,
EPCO_DATE DATE,
FOREIGN KEY (EPID) REFERENCES EPT (EPID), 
FOREIGN KEY (COID) REFERENCES COT (COID)
);

CREATE TABLE MBCOT(
COID int(10) NOT NULL,
MB_NAME CHAR (150),
MB_MEM_NUM INT (10),
MB_STYLE CHAR(150),
foreign key (COID) references COT (COID),
unique (MB_NAME)
);

CREATE table TIT(
TIID INT AUTO_INCREMENT  NOT NULL,
TIPRGR INT (3) NOT NULL,
TI_NAME CHAR (150),
UNIQUE (TIPRGR),
primary KEY (TIID)
);


CREATE TABLE TICOT (
COID INT(10) NOT NULL,
TIID INT(10) NOT NULL,
TICO_TIME TIME,
FOREIGN KEY (TIID) REFERENCES TIT (TIID), 
FOREIGN KEY (COID) REFERENCES COT (COID)
);

CREATE table PUT(
PUID INT (15) NOT NULL,
PU_NAME CHAR (150),
PU_SEX CHAR (20),
primary key (PUID)
);

CREATE TABLE PUTIT(
PUID INT(10) NOT NULL,
TIID INT(10) NOT NULL,
PUTI_PRICE INT (10),
PU_TIME TIME,
PU_DATE DATE,
TIPRGR INT (3) NOT NULL,
FOREIGN KEY (TIID) REFERENCES TIT (TIID), 
FOREIGN KEY (PUID) REFERENCES PUT (PUID),
unique (TIPRGR)

);


CREATE TABLE ART(
ARID INT auto_increment NOT NULL,
AR_NAME CHAR (150),
AR_SKILL CHAR (150),
AR_EXP INT (10),
primary key (ARID)
);

CREATE TABLE ARMBT(
ARID INT auto_increment NOT NULL,
MB_NAME CHAR (150),
MB_MEM_NUM INT (10),
AR_MEM_TIME DATE ,
foreign key (ARID) references ART(ARID)
);




